#!/usr/bin/env bash

print_color() {
  eval current_color=\$${1}
  current_color=$(echo ${current_color//\//} | tr '[:lower:]' '[:upper:]')
  echo "\"$1\":\"#$current_color\"$2"
}

theme=$1

if [ -f $theme ]; then
  # get the color declarations in said theme, assumes there is a block of text that starts with color00= and ends with new line
  eval $(awk '/^color00=/,/^$/ {print}' $theme | sed 's/#.*//')
else
  printf "No theme file %s found\n" $theme
fi;

echo "{"

for color in `seq -w 0 21`; do
  print_color "color${color}" ","
done;

print_color "color_foreground" ","
print_color "color_background"

echo "}"